
    <marquee scrollamount="5" height="80" width="99.8%">
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
      <img src="img/footer/reussir ensemble.jpeg"/>
      <img src="img/footer/index.png"/>
      <img src="img/footer/sncf.png"/>
      <img src="img/footer/bou.png"/>
      <img src="img/footer/commune.png"/>
      <img src="img/footer/europe.png"/>
    </marquee>
